services:
  postgres:
    image: postgres:15
    container_name: clinicworks-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - clinicworks-postgres-data:/var/lib/postgresql/data
      - ./apps/api/src/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  clinicworks-postgres-data:

